trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: 'your-azure-container-registry-connection' # Replace with the name of your ACR service connection
    repository: 'php-web-app'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

- task: AzureCLI@2
  displayName: 'Install kubectl'
  inputs:
    azureSubscription: 'your-azure-service-connection' # Replace with the name of your Azure service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks install-cli

- task: KubernetesManifest@0
  displayName: 'Deploy to AKS'
  inputs:
    azureSubscription: 'your-azure-service-connection' # Replace with the name of your Azure service connection
    action: 'apply'
    kubernetesServiceEndpoint: 'your-azure-service-connection' # Replace with the name of your Azure service connection
    namespace: 'default'
    manifests: '$(Build.SourcesDirectory)/k8s'
